name: Deployments example

on:
    push:
        branches: [ "main", "dev" ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'

            - name: Grant execute permission to gradlew
              run: chmod +x ./gradlew

            - name: Build with Gradle build
              uses: gradle/gradle-build-action@v2
              with:
                arguments: build

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: archive
                path: build/libs/
    
    deploy-dev:
    
      needs: [build-and-test]
      if: github.ref == 'refs/heads/dev'

      runs-on: ubuntu-latest
      environment:
        name: dev
        url: https://github.com/${{github.repository}}/releases/tag/v${{vars.DEV_VERSION}}

      steps:
        - name: Download candidate artifacts
          uses: actions/download-artifact@v4
          with:
            name: archive
            path: ./build/libs
      
        - name: release to dev
          uses: softprops/action-gh-release@v0.1.15
          with:
            tag_name: v${{ vars.DEV_VERSION }}
            token: ${{secrets.DEV_TOKEN}}
            prerelease: true
            draft: true
            name: dev
            files: build/libs/*.jar