name: file tree

on:
  workflow_dispatch:

jobs:
  file-tree:
    runs-on: self-hosted

    steps:
      - name: Install tree (Windows)
        run: choco install tree
        shell: powershell

      - name: Execute tree
        run: tree /f > filetreelist.txt
        shell: cmd
