name: file tree

on:
  workflow_dispatch:

jobs:
  file-tree:
    runs-on: self-hosted  # Windows 러너로 설정되어 있다고 가정

    steps:
      - name: Generate file tree
        run: tree /f > filetreelist.txt
        shell: cmd
